### PR TITLE
fixed a few small linter errors

### PR DESCRIPTION
**Pull request by thetornadotitan**

### CODE REVIEW

**Review by rabbitwerks — CHANGES_REQUESTED** [review]
Just one more edit, the space in the closing touchable highlight tag

**Comment by thetornadotitan** [comment]
> Just one more edit, the space in the closing touchable highlight tag

Done

**Review by rabbitwerks — APPROVED** [review]
looks good, thank you!

**Review by joshuaferr1s — APPROVED** [review]
Looks good! 😄

**Pull request merged**
