### PR TITLE
initial project commit

### PR DESCRIPTION
**Pull request by rabbitwerks**
This is the initial commit for the app-mobile repo. Containing the boilerplate React-Native and Nativebase code ready and functional. LICENSE and README.md added.

### CODE REVIEW

**Comment by sbibow** [comment]
Why do we have both `package-lock.json` and `yarn.lock`? Is this strictly necessary? Can't we use just one node package manager (either *yarn* or *npm*)?

**Comment by Sharpie360** [comment]
@sbibow yeah that is a good point. are there any benefits / drawbacks from having both versus one, and which package manager should we use, if only using one? differnces between npm and yarn?

**Comment by joshuaferr1s** [comment]
I have found yarn to be slightly more performant when it comes to the installs, but that is really the only difference

**Comment by Sharpie360** [comment]
with the release of `npx`, would that benefit us in any way for this project?

does having 2 package managers mean that it can cause management issues between the two?
ive personally always used npm for my PM, but i don't think it would make a difference to about which we use for this project. but when we choose one, we should be explicit about it. of course

**Comment by joshuaferr1s** [comment]
I can't see the need for it, however I have scarcely used it

**Comment by w3cj** [comment]
[Initialize App-Mobile Frontend repo](https://trello.com/c/bWJhge80/43-initialize-app-mobile-frontend-repo)

**Pull request merged**
